baseURL = "https://imabg.github.io/"
title = "Abhay Goswami"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 24
pagination.pagerSize = 20
disableHugoGeneratorInject = true

[params]
  author = "Abhay Goswami"
  description = "Reading notes on distributed systems, databases, and backend systems."
  tagline = "Notes on systems, databases, and what I’m reading"
  goodreadsUserId = "190374561"
  github = "https://github.com/imabg"
  linkedin = "https://www.linkedin.com/in/abhay676/"
  twitter = "https://x.com/iamabhaygoswami"
  goodreads = "https://www.goodreads.com/user/show/190374561-abhay-goswami"

[menus]
  [[menus.main]]
    name = "Papers"
    pageRef = "/papers/"
    weight = 1
  [[menus.main]]
    name = "Articles"
    pageRef = "/articles/"
    weight = 2
  [[menus.main]]
    name = "Conferences"
    pageRef = "/conferences/"
    weight = 3
  [[menus.main]]
    name = "Technical Books"
    pageRef = "/books/"
    weight = 4
  [[menus.main]]
    name = "Tags"
    pageRef = "/tags/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = true
  style = "github"
  lineNos = false

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[permalinks]
  articles = "/articles/:contentbasename/"

[security.http]
  methods = ["(?i)GET"]
  mediaTypes = ["application/.*", "text/.*"]
